"""
gbosons.dla_closure -- finite/infinite certificate for bosonic DLAs.

Generate the Lie algebra of a set of polynomial generators in (x_1..x_n, p_1..p_n)
under the canonical Poisson bracket (the leading symbol of the operator commutator)
and report its dimension and whether it closes below a total-degree cap. If the
Poisson algebra closes at finite degree, the operator DLA is finite-dimensional too
(Moyal corrections only lower degree), so this is a valid certificate for the
higher-order dichotomy of Appendix~D: the Gaussian (degree<=2) and cubic-phase
nilpotent families close; a generic cubic or a kinetic p^2 added to a cubic does not.

Run ``python -m gbosons.dla_closure`` to reproduce the verification table.
"""
from __future__ import annotations
from fractions import Fraction
from itertools import combinations_with_replacement
from math import comb

MAXDEG = 9          # basis element exceeding this total degree -> declare open/infinite
MAXDIM = 4000


def _mono_bracket(m1, m2, n):
    a, b = m1[:n], m1[n:]
    c, d = m2[:n], m2[n:]
    out = {}
    for k in range(n):
        coeff = a[k] * d[k] - b[k] * c[k]            # {x^a p^b, x^c p^d} term k
        if coeff == 0:
            continue
        ex = [a[i] + c[i] for i in range(n)] + [b[i] + d[i] for i in range(n)]
        ex[k] -= 1            # x_k lowered
        ex[n + k] -= 1        # p_k lowered
        t = tuple(ex)
        out[t] = out.get(t, 0) + coeff
    return out


def bracket(f, g, n):
    """Poisson bracket of two polynomials (dict monomial->coeff)."""
    out = {}
    for m1, c1 in f.items():
        for m2, c2 in g.items():
            for t, c in _mono_bracket(m1, m2, n).items():
                out[t] = out.get(t, Fraction(0)) + c1 * c2 * c
    return {m: c for m, c in out.items() if c != 0}


def _tdeg(m):
    return sum(m)


def _lead(f):
    return max(f, key=lambda m: (_tdeg(m), m))


def closure(gens, n):
    """Lie algebra generated by ``gens`` (list of polys). Returns
    (dim, max_total_degree, closed) where closed is False if it blew past the cap."""
    basis = {}                                   # leading monomial -> reduced poly

    def reduce(f):
        f = dict(f)
        while f:
            lm = _lead(f)
            if lm not in basis:
                break
            bp = basis[lm]
            factor = f[lm] / bp[lm]
            for m, c in bp.items():
                f[m] = f.get(m, Fraction(0)) - factor * c
            f = {m: c for m, c in f.items() if c != 0}
        return f

    def add(f):
        f = reduce(f)
        if not f:
            return False
        basis[_lead(f)] = f
        return True

    for g in gens:
        add({m: Fraction(c) for m, c in g.items()})
    changed = True
    while changed:
        changed = False
        polys = list(basis.values())
        for i in range(len(polys)):
            for j in range(i, len(polys)):
                c = bracket(polys[i], polys[j], n)
                if not c:
                    continue
                if max(_tdeg(m) for m in c) > MAXDEG or len(basis) > MAXDIM:
                    md = max((_tdeg(_lead(p)) for p in basis.values()), default=0)
                    return len(basis), md, False
                if add(c):
                    changed = True
    md = max((_tdeg(_lead(p)) for p in basis.values()), default=0)
    return len(basis), md, True


# ---- generator-set helpers (monomials as (x-exps..., p-exps...)) ----
def _xmono(n, exps):
    return tuple(exps) + (0,) * n


def momentum(n, k):
    e = [0] * (2 * n); e[n + k] = 1
    return {tuple(e): 1}


def x_polys(n, dmin, dmax):
    out = []
    for d in range(dmin, dmax + 1):
        for combo in combinations_with_replacement(range(n), d):
            a = [0] * n
            for i in combo:
                a[i] += 1
            out.append({_xmono(n, a): 1})
    return out


def quadratics(n):
    out = []
    for deg in range(3):
        for combo in combinations_with_replacement(range(2 * n), deg):
            e = [0] * (2 * n)
            for i in combo:
                e[i] += 1
            out.append({tuple(e): 1})
    return out


def gaussian(n):
    return quadratics(n)


def cubic_phase_island(n, D):
    return [momentum(n, k) for k in range(n)] + x_polys(n, 1, D)


def main():
    print(f"{'family':<34}{'n':>3}{'dim':>7}{'maxdeg':>8}  closed?  expect")
    for n in (1, 2, 3):
        dim, md, ok = closure(gaussian(n), n)
        print(f"{'Gaussian (deg<=2)':<34}{n:>3}{dim:>7}{md:>8}  {str(ok):<7}  (2n+1)(n+1)={(2*n+1)*(n+1)}")
    for n in (1, 2, 3, 4):
        dim, md, ok = closure(cubic_phase_island(n, 3), n)
        print(f"{'cubic-phase island (D=3)':<34}{n:>3}{dim:>7}{md:>8}  {str(ok):<7}  n+C(n+3,3)={n + comb(n + 3, 3)}")
    for n in (1, 2):
        gens = gaussian(n) + [{_xmono(n, [3] + [0] * (n - 1)): 1}]
        dim, md, ok = closure(gens, n)
        print(f"{'Gaussian + x^3 (universal)':<34}{n:>3}{dim:>7}{md:>8}  {str(ok):<7}  OPEN/infinite")


if __name__ == "__main__":
    main()
